spring:
#关闭Thymeleaf的缓存
  thymeleaf:
    cache: false
#国际化资源真实位置
  messages:
    basename: i18n.login
#mybatis配置
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sovzn?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
#整合mybatis
#-------包名
mybatis:
  type-aliases-package: com.syc.pojo
#-------mapper文件位置
  mapper-locations: classpath:resource/mybatis/mapper/*.xml

  # 端口号
server:
  port: 8888

#mybatis分页
